version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: farmosync-mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: farmosync
    volumes:
      - mongo_data:/data/db
    networks:
      - farmosync-network

  mongodb-init:
    image: mongo:6.0
    container_name: farmosync-mongodb-init
    depends_on:
      - mongodb
    entrypoint: [ "mongosh", "--host", "mongodb:27017", "--eval", "try { rs.status().ok } catch (err) { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]}) }" ]
    networks:
      - farmosync-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: farmosync-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      
      # Listeners para comunicação interna do Docker e externa do Host local
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # Cluster ID necessário para o KRaft
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # Otimizações de consistência e replicação para Single Broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - farmosync-network
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: farmosync-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - farmosync-network

volumes:
  mongo_data:
    driver: local
  kafka_data:
    driver: local

networks:
  farmosync-network:
    driver: bridge
