server:
  port: 8082

spring:
  application:
    name: prescription-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/farmosync_prescription
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: prescription-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

app:
  kafka:
    topics:
      venda-emitida: "venda-emitida-topic"
      receita-validada: "receita-validada-topic"

